### PR TITLE
Overhauled installation script

### PR DESCRIPTION
**Pull request by omrisim210**
Since previously the bulk of the work was done in Powershell anyway I rewrote the script in pure Powershell, you can double-click it just like a batch file on any modern Windows (at least Vista I think, but I don't if 100% of my script is compatible with old versions).

It's based on your code but I formatted it according to [best practices](https://github.com/PoshCode/PowerShellPracticeAndStyle/), used native Powershell solutions over CMD ones (e.g. `Stop-Process` instead of `taskkill`) and rewrote some of the behavior to act like I think it should.

The main changes are that it saves everything in a temporary directory that's unique to every script invocation (it looks like this: `$env:TEMP\BlockTheSpot-2020-04-01_12-28-25`) and deletes the files and the directory after it finishes.  
Before exiting it also starts Spotify, and I added some error handling to a few points that could fail so it shows the error and pauses.

This is [bikeshedding](https://en.wikipedia.org/wiki/Law_of_triviality) and there are probably a few small things to fix but whatever. What do you think?

### CODE REVIEW

**Comment by rednek46** [comment]
> Since previously the bulk of the work was done in Powershell anyway I rewrote the script in pure Powershell, you can double-click it just like a batch file on any modern Windows (at least Vista I think, but I don't if 100% of my script is compatible with old versions).
> 
> It's based on your code but I formatted it according to [best practices](https://github.com/PoshCode/PowerShellPracticeAndStyle/), used native Powershell solutions over CMD ones (e.g. `Stop-Process` instead of `taskkill`) and rewrote some of the behavior to act like I think it should.
> 
> The main changes are that it saves everything in a temporary directory that's unique to every script invocation (it looks like this: `$env:TEMP\BlockTheSpot-2020-04-01_12-28-25`) and deletes the files and the directory after it finishes.
> Before exiting it also starts Spotify, and I added some error handling to a few points that could fail so it shows the error and pauses.
> 
> This is [bikeshedding](https://en.wikipedia.org/wiki/Law_of_triviality) and there are probably a few small things to fix but whatever. What do you think?

Thanks. this script is way better than mine. 
the reason i still used the batch file last time is that, double clicking on a .ps1 file opens it in notepad rather than executing it. 

so i added 
`;;;===,,,@echo off` 
`;;;===,,,findstr /v "^;;;===,,," "%~f0" > "%~dp0ps.ps1"  `
`;;;===,,,PowerShell.exe -ExecutionPolicy Bypass -Command "& '%~dp0ps.ps1'" `
`;;;===,,,del /s /q "%~dp0ps.ps1" >NUL 2>&1 `
`;;;===,,,pause`
at the start of the ps script and changed the extension to bat. now the script creates a .ps1 file and executes it. i thought it would be easier for people to run a batch file than a ps script.

**Comment by rednek46** [comment]
> Since previously the bulk of the work was done in Powershell anyway I rewrote the script in pure Powershell, you can double-click it just like a batch file on any modern Windows (at least Vista I think, but I don't if 100% of my script is compatible with old versions).
> 
> It's based on your code but I formatted it according to [best practices](https://github.com/PoshCode/PowerShellPracticeAndStyle/), used native Powershell solutions over CMD ones (e.g. `Stop-Process` instead of `taskkill`) and rewrote some of the behavior to act like I think it should.
> 
> The main changes are that it saves everything in a temporary directory that's unique to every script invocation (it looks like this: `$env:TEMP\BlockTheSpot-2020-04-01_12-28-25`) and deletes the files and the directory after it finishes.
> Before exiting it also starts Spotify, and I added some error handling to a few points that could fail so it shows the error and pauses.
> 
> This is [bikeshedding](https://en.wikipedia.org/wiki/Law_of_triviality) and there are probably a few small things to fix but whatever. What do you think?

I ran the script without spotify. It got many error.
1. Spotify wont install, exits with error like "Cant create required files". fixed by creating a folder named Spotify at %appdata%.
2. The script tries to remove the installer as soon as the installer is run. which will return error as installation is in progress and the file cant be deleted.
3. It doesn't patch or backup the orignal dll.

**Comment by rednek46** [comment]
@omrisim210 i will pull this anyway and will make some changes.

**Comment by rednek46** [comment]
Checkout the new bat file in my repo. @omrisim210

**Comment by omrisim210** [comment]
> Spotify wont install, exits with error like "Cant create required files". fixed by creating a folder named Spotify at %appdata%.

My bad, I had a typo in my code. My brain confuses `Sleep` with `Pause` for some reason.  
Anyway I'm not happy with that behavior, because this basically duplicates the default powershell behavior of exiting and printing an error, but it also pauses for people who double click the script so they can see the output after the script finishes running.
[Here's the typo](
https://github.com/omrisim210/BlockTheSpot/blob/0f901aa032f9e28887103fc62b029cc46cb45592/BlockTheSpot.ps1#L66) (it actually appears twice), but I fixed it on my master branch.

> The script tries to remove the installer as soon as the installer is run. which will return error as installation is in progress and the file cant be deleted.

Huh, I didn't think about that but the fix was literally an extra parameter to `Start-Process` and it's fixed now.

> It doesn't patch or backup the orignal dll

Another mistype, sorry again. Should also be fixed in my master branch.

> Doesn't clear the temp files

Huh, that's weird.  
My code saves the temp file directory (`%TEMP%\BlockTheSpot-xxxx-xx-xx_xx-xx-xx"`) to a variable, goes back to where the user was before (useful if you run the script from an existing powershell session) and deletes the directory if it's empty (which it should be, since I took care to delete the spotify installer, the patch zip and the patch files beforehand).  
The way I check if it's empty works on my system (this is the same code I use in my script, I just used aliases for brevity):
```powershell
mkdir delete_me | cd
if ((ls | measure).count -eq 0) { echo empty }
else { echo 'not empty' } 
# should print "empty"
```
There might be an error related to Spotify's installation (as I didn't test it on a machine without Spotify), so it might be a good idea to delete the entire folder with `-Force` instead of deleting every single file we use.  
The rationale behind the way I did it was to not delete any file that the user might've put there, but it's a temporary folder and with those you generally have no guarantee that your files will stick around so it's best to not put anything you can't risk being deleted in there anyway.

**Comment by omrisim210** [comment]
I just looked at the [original installation script](https://github.com/master131/BlockTheSpot/blob/master/install.bat) and it seems like it could still work for the new BTS. 
I like how it doesn't create a new powershell file, but instead has the dll's raw binary data embedded in it after line 31 and it just writes it to the Spotify installation folder.

It doesn't handle backups but that can be added in a just a few lines, and due to the nature of this method the patch can only be one file.
I can think of a few solutions for this:
 * Mrpond's code can have default options, and only load custom options if it finds a `config.ini` file next to the patch dll.
 * We can embed the current patch's zip file, write it to the Spotify directory, extract and then delete it. This doesn't require any changes to the patch code but does require some extra powershell code.

The original installer also doesn't download the installer on its own, but it should be very doable with some powershell and maybe I can find a way to do it with only one invocation (since as I mentioned before, powershell startup is a bit slow on my system).

One advantage of the method I'm proposing is that if you already have Spotify installed the patch installer contains all of the data for the patch, no need to download anything. It doesn't matter too much for such a tiny script but it's still cleaner in my opinion.

**Pull request merged**
